### ISSUE TITLE
Paper link is outdated

### ISSUE THREAD

**Issue by kbertalan** [pepeiborra/control-monad-exception#13]
The link in the readme and the github site (https://dl.dropboxusercontent.com/s/lgm12trtl0swtra/PADL10.pdf?dl=1) results in a 404 not found page.

**Comment by pepeiborra** [comment]
Here's a working link: https://www.scribd.com/document/25467100/Explicitly-Typed-Exceptions-for-Haskell-PADL-10

**Comment by kbertalan** [comment]
Thanks @pepeiborra 
Do you think this link can be used to replace the broken dropbox link in the documentation?

**Comment by pepeiborra** [comment]
Yes, that would be great
